# These are supported funding model platforms

open_collective: fahrettinaksoy # Replace with a single Open Collective username
buy_me_a_coffee: fahrettinaksoy # Replace with a single Buy Me a Coffee username
thanks_dev: fahrettinaksoy # Replace with a single thanks.dev username
