# These are supported funding model platforms

patreon: fahrettinaksoy # Replace with a single Patreon username
open_collective: fahrettinaksoy # Replace with a single Open Collective username
ko_fi: fahrettinaksoy # Replace with a single Ko-fi username
liberapay: fahrettinaksoy # Replace with a single Liberapay username
issuehunt: fahrettinaksoy # Replace with a single IssueHunt username
lfx_crowdfunding: fahrettinaksoy # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
buy_me_a_coffee: fahrettinaksoy # Replace with a single Buy Me a Coffee username
thanks_dev: fahrettinaksoy # Replace with a single thanks.dev username
