//! Verifying that an index was signed by a key this machine already trusts.
//!
//! The first link of the chain `market.rs` describes, and the one it said was
//! missing:
//!
//! ```text
//!   a pinned key          →  registry.json          (here)
//!   registry.json         →  manifest.json          (market::refresh)
//!   manifest.json         →  every file it ships    (pkg::verify)
//! ```
//!
//! Until this existed `Trust::Signed` was a shape with no implementation, so a
//! third-party source could be *fetched* but never *believed* — the
//! architecture was "ready" for a door it could not actually hold shut. It can
//! now.
//!
//! ## minisign, and why it costs nothing
//!
//! The registry gets its own ed25519 key pair, separate from the updater's. minisign is ed25519 with a file format around it, it is what
//! Tauri's updater already uses to check a downloaded binary, and
//! `minisign-verify` is therefore **already in `Cargo.lock`** — measured:
//! taking it directly adds a dependency edge and **zero packages**.
//!
//! It also means the key ceremony has a tool that exists: `minisign -G`, or
//! Tauri's own `signer generate`. A scheme needing a bespoke tool is one whose
//! ceremony never happens.
//!
//! ## The official key is here now, and what that does and does not mean
//!
//! [`PINNED`] carries it. For a long time it was empty and said so loudly,
//! because inventing a placeholder would have been worse than the gap — every
//! later reader would have believed the chain was closed. The ceremony has
//! since happened (`tools/keys.sh`), so:
//!
//! * A build can verify an index signed by the official registry, and
//!   `Trust::Signed` is a check rather than a refusal.
//! * **The index is signed and published.** This half of the chain being closed
//!   signs nothing on its own; the packages repository signs its own
//!   `registry.json` with the private half, by hand, on the machine that holds
//!   it — which is why that key is deliberately not a CI secret. That happened,
//!   and the published signature verifies against [`PINNED`]. The index is
//!   generated, so each regeneration needs signing again; a signature that no
//!   longer matches is a refusal, not a downgrade.
//! * An organisation running its own mirror pins **its own** key through
//!   `policy.market.additionalKeys`, and that is added to this list rather than
//!   replacing it: a machine that forgot the official key while trusting a
//!   mirror could not go back without a reinstall.
//!
//! ## Rotation is designed in, because it cannot be added later
//!
//! A pinning with no rotation plan is one whose only answer to a leak is
//! *everybody update the app*. So [`Keys`] holds a **set**, and a
//! machine trusts an index signed by any key in it. A new key is introduced by
//! a `known-keys.json` that is itself signed by a key already trusted —
//! [`adopt`] — so the trust moves forward on the strength of the old key
//! rather than on the strength of having been downloaded.
//!
//! What that deliberately cannot do is *remove* the compromised key on its
//! own say-so. A leaked key can sign a `known-keys.json` naming only itself,
//! so revocation is a build, and [`Keys::retired`] is what a build carries.

use crate::error::{Code, Error, Result};
use serde::{Deserialize, Serialize};

/// Keys compiled into this build.
///
/// One: the official registry's content key, generated by the ceremony in
/// `tools/keys.sh generate` and **not** the updater's — a leak of either
/// forges one thing, never both, and `key_ceremony.rs` refuses a build where
/// they are the same.
///
/// Adding to this list is a deliberate act, and
/// `an_added_key_is_a_deliberate_act` is what makes that true rather than
/// hoped: `tools/keys.sh` is the ceremony, and every sentence that used to say
/// the chain was open is wrong wherever it survives.
pub const PINNED: &[&str] = &[
    // 256219FF1F9A0F1B — the official StackVo package registry.
    "RWQbD5of/xliJY7WXb+sFE+Nba3QD0TgXneUNgBIsHf7+BVz2oT0gs0r",
];

/// Keys this build refuses even when something presents them.
///
/// Separate from simply not being in [`PINNED`], because rotation moves keys
/// **in** at run time: a leaked key that is merely absent can be reintroduced
/// by a `known-keys.json` it signed itself. One listed here cannot, whatever
/// signs the document that names it.
pub const RETIRED: &[&str] = &[];

/// A minisign public key, as it appears in a `.pub` file's second line.
///
/// Stored as the base64 line rather than parsed bytes: it is what a person
/// copies out of a key file, what a policy file carries, and what an error
/// message has to be able to print back.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PublicKey(pub String);

impl PublicKey {
    /// The key id minisign puts in front of every signature.
    ///
    /// Eight bytes, shown so a refusal can say *which* key signed the thing it
    /// refused — "signed by a key this machine does not trust" is a sentence
    /// somebody can act on only if it names the key.
    pub fn id(&self) -> String {
        // The untrusted-comment line is optional in a `.pub` file; the key line
        // is the one that matters and is what this holds.
        let trimmed = self.0.trim();
        trimmed.chars().take(16).collect()
    }

    fn parse(&self) -> Result<minisign_verify::PublicKey> {
        minisign_verify::PublicKey::from_base64(self.0.trim()).map_err(|e| {
            Error::new(
                Code::InvalidInput,
                format!("\"{}…\" is not a minisign public key: {e}", self.id()),
            )
            .with_hint(
                "A key is the second line of a minisign `.pub` file — the one that is not \
                 a comment."
                    .to_string(),
            )
        })
    }
}

/// The signature text, whichever envelope it arrived in.
///
/// Two tools produce minisign signatures for this project and they disagree
/// about the wrapper, not about the cryptography:
///
/// * `minisign -S` writes the signature as text — an untrusted comment, the
///   base64 signature, a trusted comment, and the global signature.
/// * `tauri signer sign` writes **that same file, base64-encoded again**,
///   because Tauri's updater manifest carries a signature as one JSON string.
///
/// Accepting only the first was measured, not assumed: a key generated with
/// `tauri signer generate` and used with `tauri signer sign` produced a
/// `registry.json.minisig` this verifier refused, and the refusal said
/// "invalid encoding in minisign data" — a message about bytes, for a problem
/// that is about an envelope, raised at the one moment somebody is trying to
/// close the chain for the first time.
///
/// It matters because the updater key and the content key are deliberately
/// separate, and the thing that makes paying for two signing
/// surfaces worthwhile is that the *procedure* is shared — same storage, same
/// access list, same rotation steps. A registry key that needed a second tool
/// would be a second procedure, and a second procedure is the one nobody
/// maintains.
///
/// So the envelope is peeled and the signature is checked exactly as before.
/// This widens what can be *read*; it does not widen what is *accepted* — a
/// wrapper around bytes no trusted key signed still fails, one line down.
fn unwrapped(signature: &str) -> String {
    let trimmed = signature.trim();
    // Already plain: a minisign signature file's first line is its comment.
    if trimmed.starts_with("untrusted comment:") {
        return trimmed.to_string();
    }
    let Some(decoded) = decode_base64(trimmed) else {
        return trimmed.to_string();
    };
    match String::from_utf8(decoded) {
        // Only when what came out is itself a signature file. Anything else is
        // handed on untouched so the error names the real problem rather than
        // this function's guess about it.
        Ok(text) if text.trim_start().starts_with("untrusted comment:") => text,
        _ => trimmed.to_string(),
    }
}

/// Standard base64, ignoring the line breaks a wrapped file may carry.
///
/// Hand-rolled because this crate has no base64 dependency and adding one to
/// peel a wrapper would be a supply-chain entry for sixteen lines of table
/// lookup. Returns `None` for anything that is not base64, which is the answer
/// [`unwrapped`] wants: not base64 means not wrapped.
fn decode_base64(text: &str) -> Option<Vec<u8>> {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    let mut out = Vec::new();
    let mut accumulator: u32 = 0;
    let mut bits = 0u32;
    let mut padding = 0;

    for byte in text.bytes() {
        if byte.is_ascii_whitespace() {
            continue;
        }
        if byte == b'=' {
            padding += 1;
            continue;
        }
        // A character after the padding has started is not base64 at all.
        if padding > 0 {
            return None;
        }
        let value = ALPHABET.iter().position(|c| *c == byte)? as u32;
        accumulator = (accumulator << 6) | value;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push((accumulator >> bits) as u8);
            accumulator &= (1 << bits) - 1;
        }
    }

    // Leftover bits must be zero padding, never data: `RW==` and `RWA=` differ
    // by a bit that a lenient decoder would drop, and a decoder that drops bits
    // makes two different inputs decode to one output.
    if bits >= 8 || accumulator != 0 || padding > 2 || out.is_empty() {
        return None;
    }
    Some(out)
}

/// Everything this machine will accept a signature from.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Keys {
    /// Trusted, in the order they were learned: compiled in first, adopted
    /// after.
    pub trusted: Vec<PublicKey>,
    /// Refused whatever presents them. Only a build can add to this.
    #[serde(default)]
    pub retired: Vec<PublicKey>,
}

impl Keys {
    /// What this build trusts before anything is adopted.
    pub fn pinned() -> Self {
        Self {
            trusted: PINNED.iter().map(|k| PublicKey(k.to_string())).collect(),
            retired: RETIRED.iter().map(|k| PublicKey(k.to_string())).collect(),
        }
    }

    /// The same, plus whatever an administrator pinned through policy.
    ///
    /// `policy.market.additionalKeys` was written for this and had no reader
    /// until now — its own comment says "for an organisation signing its own
    /// mirror". Added rather than replacing: a machine that forgot the
    /// official key while trusting a mirror would be one that could not go
    /// back to the official registry without a reinstall.
    ///
    /// A retired key is refused here too. Policy is an administrator's file,
    /// and an administrator can be handed a key that has since leaked.
    pub fn with_policy(mut self, keys: &[String]) -> Self {
        for key in keys {
            let key = PublicKey(key.trim().to_string());
            if key.0.is_empty() || self.trusted.contains(&key) {
                continue;
            }
            if self.is_retired(&key) {
                tracing::warn!(key = %key.id(), "policy names a retired key; ignoring it");
                continue;
            }
            self.trusted.push(key);
        }
        self
    }

    pub fn is_empty(&self) -> bool {
        self.trusted.is_empty()
    }

    fn is_retired(&self, key: &PublicKey) -> bool {
        self.retired.iter().any(|k| k.0.trim() == key.0.trim())
    }

    /// Check `signature` over `bytes` against every key, and say which one
    /// worked.
    ///
    /// Every key is tried because rotation means more than one is legitimate
    /// at once. A retired key is skipped **before** it is tried rather than
    /// after: a signature that verifies and is then discarded is one somebody
    /// eventually refactors into an acceptance.
    pub fn verify(&self, bytes: &[u8], signature: &str) -> Result<PublicKey> {
        if self.is_empty() {
            return Err(Error::new(
                Code::Unsupported,
                "no registry key is pinned in this build, so a signature cannot be checked",
            )
            .with_hint(crate::hints::NO_REGISTRY_KEY));
        }

        let text = unwrapped(signature);
        let signature = minisign_verify::Signature::decode(text.trim()).map_err(|e| {
            Error::new(
                Code::InvalidManifest,
                format!("the signature file is not a minisign signature: {e}"),
            )
        })?;

        let mut tried = Vec::new();
        for key in &self.trusted {
            if self.is_retired(key) {
                continue;
            }
            let parsed = key.parse()?;
            // `true` — accept minisign's older, non-prehashed signatures too.
            //
            // This was `false` first, on the reasoning that the two modes sign
            // different things and accepting both would let a signature made
            // over one be valid for another. Working through it, that is not
            // what happens: the mode is declared in the signature file, the
            // verifier hashes or does not hash accordingly, and presenting a
            // signature of one kind as the other simply fails to verify. There
            // is no mode-confusion to win.
            //
            // So refusing legacy bought nothing and cost something real — an
            // organisation whose mirror was signed by an older `minisign`
            // would have been refused with no way to tell why from the
            // message. `policy.market.additionalKeys` exists for exactly those
            // people.
            if parsed.verify(bytes, &signature, true).is_ok() {
                return Ok(key.clone());
            }
            tried.push(key.id());
        }

        Err(Error::new(
            Code::PermissionDenied,
            format!(
                "the index is signed, but by none of the {} key(s) this machine trusts ({})",
                tried.len(),
                tried.join(", ")
            ),
        )
        .with_hint(crate::hints::SIGNED_BY_UNKNOWN_KEY))
    }
}

/// A `known-keys.json`: the document that introduces a new key.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KnownKeys {
    pub schema_version: u32,
    /// Monotonic, for the same reason the index has one: replaying an older
    /// document is how a key that was rotated away comes back.
    pub sequence: u64,
    pub keys: Vec<PublicKey>,
}

/// A rotation document has to be newer than the one already applied.
///
/// Its own function so it can be checked directly: reaching it through
/// [`adopt`] needs a signature over a JSON document, and a test that cannot
/// reach a rule is a rule with no test. Replaying yesterday's document is how
/// a key that was rotated away comes back.
fn moves_forward(sequence: u64, last: u64) -> Result<()> {
    if sequence <= last {
        return Err(Error::new(
            Code::Conflict,
            format!(
                "known-keys.json is at sequence {sequence} and this machine already has \
                 {last} — an older document is how a rotated-away key comes back"
            ),
        ));
    }
    Ok(())
}

/// Learn the keys in `document`, on the strength of a key already trusted.
///
/// The rotation step. Three things it will not do, each of which
/// would turn rotation into a way in:
///
/// * **Accept an unsigned document.** The signature is checked against the
///   keys already held, before a field is read.
/// * **Go backwards.** A lower `sequence` is refused, so yesterday's document
///   cannot reintroduce a key today's removed.
/// * **Un-retire.** A key in [`Keys::retired`] stays out even when a perfectly
///   valid document names it, because the document could have been signed by
///   the leaked key itself.
pub fn adopt(
    current: &Keys,
    document: &[u8],
    signature: &str,
    last_sequence: u64,
) -> Result<(Keys, PublicKey)> {
    let by = current.verify(document, signature)?;

    let parsed: KnownKeys = serde_json::from_slice(document).map_err(|e| {
        Error::new(
            Code::InvalidManifest,
            format!("known-keys.json is unreadable: {e}"),
        )
    })?;

    if parsed.schema_version != 1 {
        return Err(Error::new(
            Code::Unsupported,
            format!(
                "known-keys.json declares schema version {}, and this build reads 1",
                parsed.schema_version
            ),
        ));
    }

    moves_forward(parsed.sequence, last_sequence)?;

    let mut next = current.clone();
    next.trusted.clear();
    for key in parsed.keys {
        if current.is_retired(&key) {
            // Named and skipped rather than failing the whole document: the
            // rest of a rotation is still worth applying, and a build that
            // retired a key means it whatever a document says.
            tracing::warn!(key = %key.id(), "known-keys.json names a retired key; ignoring it");
            continue;
        }
        next.trusted.push(key);
    }

    if next.trusted.is_empty() {
        return Err(Error::new(
            Code::InvalidManifest,
            "known-keys.json would leave this machine trusting nothing",
        ));
    }

    Ok((next, by))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A real minisign key and a real signature it made, over the bytes
    /// `test`. Taken from `minisign-verify`'s own test vector, which is the
    /// point: a key pair this file generated for itself would let it agree
    /// with its own idea of what minisign is, and the QR encoder already cost
    /// this repository that lesson once.
    ///
    /// Without a **passing** verification here, every other test in this
    /// module still passes when `verify` is broken to always fail.
    const TEST_PUB: &str = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3";
    const TEST_PAYLOAD: &[u8] = b"test";
    const TEST_SIG: &str = "untrusted comment: signature from minisign secret key
RWQf6LRCGA9i59SLOFxz6NxvASXDJeRtuZykwQepbDEGt87ig1BNpWaVWuNrm73YiIiJbq71Wi+dP9eKL8OC351vwIasSSbXxwA=
trusted comment: timestamp:1555779966\tfile:test
QtKMXWyYcwdpZAlPF7tE2ENJkRd1ujvKjlj1m9RtHTBnZPa5WKU5uWRs5GoP5M/VqE81QFuMKI5k/SfNQUaOAA==";

    /// A different, valid key that did not make that signature.
    const OTHER_PUB: &str = "RWTf9M1kNu0hxJVCiHNYRJ3n8UGQeb1XwSpDGSLYqAqZOHTNVwQBrq0X";

    /// The same signature `tauri signer sign` writes: base64 around the whole
    /// file.
    ///
    /// Produced by running the real tool against a throwaway key — generated
    /// for this test, used for nothing else, and its private half never left
    /// the scratch directory it was made in. That provenance is the point.
    /// `TEST_SIG` above comes from `minisign-verify`'s own vector because a
    /// verifier checked against a key it generated itself only agrees with its
    /// own idea of minisign; this one has to come from the **other** tool,
    /// because what it is checking is precisely that the other tool's output
    /// arrives readable.
    const TAURI_PUB: &str = "RWRhXQLolHxl28PGylOViTTfp07ldv/HoX/8h9MY9Od8SM+fkDbng0Yt";
    const TAURI_PAYLOAD: &[u8] = b"stackvo-registry\n";
    const TAURI_WRAPPED_SIG: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSaFhRTG9sSHhsMjJlMlg2WGh2NVVmR0h6dFA3eS8wQ0hNOGNpVGdLVHlNZzFsZXZRdW1SSnQ2K1NRS3FwV3ZWVnhJUEoxcHNYL0l3N2Q4VWdBT200a0Q1NnhpdUd6UUFvPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzg3NTEyMjM5CWZpbGU6cGF5bG9hZC50eHQKRU42UEFaMmszMmJkYmVkdTc2d3A2MnhLZlNJTlNtN3ZaM28vRFZEMXE4OTBYbTNXcFNjaXBnQ2VhYmxwbHJQSkdGcHZKeWtxNFZvNWdxTmswTjFDQWc9PQo=";

    /// The finding that made [`unwrapped`] exist.
    ///
    /// The updater key and the content key are kept separate, and that is paid
    /// for with two signing surfaces; what makes it worth paying is that the
    /// *procedure* is shared. `tauri signer` is the tool the updater ceremony
    /// already uses, and until this it produced a `registry.json.minisig` the
    /// app refused — so the registry key would have needed a second tool, which
    /// is the second procedure that goes unmaintained.
    #[test]
    fn a_signature_from_the_tool_the_updater_ceremony_uses_is_read() {
        let key = keys(&[TAURI_PUB]);
        let accepted = key
            .verify(TAURI_PAYLOAD, TAURI_WRAPPED_SIG)
            .expect("the base64 envelope tauri signer writes is peeled");
        assert_eq!(accepted.0, TAURI_PUB);
    }

    /// Peeling widens what can be *read*, never what is *accepted*.
    #[test]
    fn a_wrapped_signature_by_an_untrusted_key_is_still_refused() {
        assert!(keys(&[OTHER_PUB])
            .verify(TAURI_PAYLOAD, TAURI_WRAPPED_SIG)
            .is_err());
    }

    /// And the envelope is not a way to change what was signed.
    #[test]
    fn a_wrapped_signature_over_other_bytes_is_refused() {
        assert!(keys(&[TAURI_PUB])
            .verify(b"something else", TAURI_WRAPPED_SIG)
            .is_err());
    }

    /// Not base64 and not a signature: the error has to name the real problem
    /// rather than the unwrapper's guess about it.
    #[test]
    fn something_that_is_neither_envelope_is_reported_as_what_it_is() {
        let refused = keys(&[TEST_PUB]).verify(TEST_PAYLOAD, "not a signature at all");
        let message = refused.unwrap_err().message;
        assert!(
            message.contains("not a minisign signature"),
            "the refusal talks about the envelope instead of the file: {message}"
        );
    }

    fn keys(list: &[&str]) -> Keys {
        Keys {
            trusted: list.iter().map(|k| PublicKey(k.to_string())).collect(),
            retired: Vec::new(),
        }
    }

    /// The gap this module exists to close, stated as a test: with nothing
    /// pinned, a signed refresh is refused rather than quietly downgraded.
    #[test]
    fn a_build_with_no_pinned_key_refuses_rather_than_accepting() {
        let error = Keys::default()
            .verify(b"anything", "irrelevant")
            .unwrap_err();
        assert_eq!(error.code, Code::Unsupported);
        assert!(
            error.message.contains("no registry key"),
            "{}",
            error.message
        );
    }

    /// The shipped key is a real one, and adding another is a deliberate act.
    ///
    /// This used to assert the list was **empty**, which was the right gate for
    /// as long as the ceremony had not happened: it made the arrival of a key
    /// something a person had to notice. The ceremony has happened, so the gate
    /// turns over rather than going away — what it now refuses is a key that
    /// cannot be parsed, and a list that quietly grows.
    ///
    /// One, deliberately. A second pinned key is how a build starts trusting
    /// two publishers without anybody deciding to, and rotation does not need
    /// one — `adopt` moves a new key in at run time, signed by the old.
    #[test]
    fn an_added_key_is_a_deliberate_act() {
        assert_eq!(
            PINNED.len(),
            1,
            "the pinned set changed size. A build trusts every key in it, so \
             adding one is a decision to be argued for rather than a diff."
        );
        let keys = Keys::pinned();
        assert!(!keys.is_empty());
        for key in &keys.trusted {
            key.parse()
                .expect("a pinned key that cannot be parsed verifies nothing");
        }
    }

    /// And it is the *content* key, not the updater's.
    ///
    /// The whole point of two key pairs, checked from this side as well as from
    /// `key_ceremony.rs`: that one reads the tree, this one reads the constant
    /// the code actually uses.
    #[test]
    fn the_pinned_key_is_not_the_one_the_updater_carries() {
        let conf = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tauri.conf.json"),
        )
        .expect("tauri.conf.json is readable");
        for key in PINNED {
            assert!(
                !conf.contains(key),
                "the registry key is also the updater key — one leak would forge \
                 both a signed installer and signed packages"
            );
        }
    }

    #[test]
    fn a_policy_key_is_added_rather_than_replacing_what_is_pinned() {
        let with = keys(&[TEST_PUB]).with_policy(&[OTHER_PUB.to_string()]);
        assert_eq!(with.trusted.len(), 2);
        assert_eq!(with.trusted[0].0, TEST_PUB, "the pinned key stays first");

        // Blank, repeated and absent values are not new keys.
        assert_eq!(
            with.clone().with_policy(&[OTHER_PUB.into()]).trusted.len(),
            2
        );
        assert_eq!(
            with.clone().with_policy(&["   ".to_string()]).trusted.len(),
            2
        );
        assert_eq!(with.with_policy(&[]).trusted.len(), 2);
    }

    /// An administrator can be handed a key that has since leaked, so policy
    /// does not get to reintroduce a retired one either.
    #[test]
    fn policy_cannot_reintroduce_a_retired_key() {
        let current = Keys {
            trusted: vec![PublicKey(TEST_PUB.into())],
            retired: vec![PublicKey(OTHER_PUB.into())],
        };
        let after = current.with_policy(&[OTHER_PUB.to_string()]);
        assert_eq!(after.trusted.len(), 1);
    }

    #[test]
    fn a_malformed_key_or_signature_is_reported_as_one() {
        let error = keys(&[TEST_PUB])
            .verify(b"x", "not a signature")
            .unwrap_err();
        assert!(error.message.contains("signature"), "{}", error.message);

        let error = keys(&["not a key"])
            .verify(TEST_PAYLOAD, TEST_SIG)
            .unwrap_err();
        assert!(error.message.contains("public key"), "{}", error.message);
    }

    /// The positive path, against a real signature. Everything else in this
    /// module is a refusal, and a verifier that refuses everything passes all
    /// of them.
    #[test]
    fn a_real_signature_from_a_trusted_key_verifies_and_says_which_one() {
        let by = keys(&[TEST_PUB])
            .verify(TEST_PAYLOAD, TEST_SIG)
            .expect("the vector's own key made this signature");
        assert_eq!(by.0, TEST_PUB);
    }

    /// And it is the *bytes* that are verified. One changed character is a
    /// different document, which is the whole point of signing an index.
    #[test]
    fn a_single_changed_byte_is_refused() {
        let error = keys(&[TEST_PUB]).verify(b"Test", TEST_SIG).unwrap_err();
        assert_eq!(error.code, Code::PermissionDenied);
    }

    /// Rotation, working: a machine holding several keys accepts an index
    /// signed by any of them, whichever order they were learned in.
    #[test]
    fn any_trusted_key_may_have_signed_it() {
        assert!(keys(&[OTHER_PUB, TEST_PUB])
            .verify(TEST_PAYLOAD, TEST_SIG)
            .is_ok());
        assert!(keys(&[TEST_PUB, OTHER_PUB])
            .verify(TEST_PAYLOAD, TEST_SIG)
            .is_ok());
    }

    #[test]
    fn a_signature_from_an_untrusted_key_names_the_keys_that_were_tried() {
        let error = keys(&[OTHER_PUB])
            .verify(TEST_PAYLOAD, TEST_SIG)
            .unwrap_err();
        assert_eq!(error.code, Code::PermissionDenied);
        assert!(
            error.message.contains(&PublicKey(OTHER_PUB.into()).id()),
            "the refusal has to name the key that was tried: {}",
            error.message
        );
    }

    /// A retired key does not verify even when it is also listed as trusted —
    /// which is the state a build enters the moment a leak is discovered.
    #[test]
    fn a_retired_key_cannot_verify_even_while_it_is_still_trusted() {
        let leaked = Keys {
            trusted: vec![PublicKey(TEST_PUB.into())],
            retired: vec![PublicKey(TEST_PUB.into())],
        };
        let error = leaked.verify(TEST_PAYLOAD, TEST_SIG).unwrap_err();
        assert_eq!(error.code, Code::PermissionDenied);
    }

    /// An unverifiable rotation document never reaches its own fields.
    ///
    /// The ordering is the property: `adopt` checks the signature before it
    /// parses, so a document whose *contents* look right cannot get anywhere
    /// on the strength of having been downloaded.
    #[test]
    fn a_rotation_document_is_verified_before_it_is_read() {
        let document = serde_json::to_vec(&KnownKeys {
            schema_version: 1,
            sequence: 4,
            keys: vec![PublicKey(OTHER_PUB.into())],
        })
        .unwrap();

        // Perfectly well-formed, signed by nothing this machine trusts.
        let error = adopt(&keys(&[TEST_PUB]), &document, TEST_SIG, 0).unwrap_err();
        assert_eq!(error.code, Code::PermissionDenied);

        // And with no key at all, the refusal is the other one.
        let error = adopt(&Keys::default(), &document, TEST_SIG, 0).unwrap_err();
        assert_eq!(error.code, Code::Unsupported);
    }

    /// The rotation path, past the signature: `test` verifies, so `adopt`
    /// reaches its own parsing and fails there rather than on trust. That
    /// ordering is the thing being asserted.
    #[test]
    fn a_signed_rotation_gets_past_verification_to_its_own_rules() {
        // The vector signs the literal bytes `test`, so that is the document.
        // Standing in for a real known-keys.json, which is why this asserts on
        // the refusal rather than on a parsed result.
        let error = adopt(&keys(&[TEST_PUB]), TEST_PAYLOAD, TEST_SIG, 0).unwrap_err();
        assert_eq!(
            error.code,
            Code::InvalidManifest,
            "the signature verified and parsing is what failed: {}",
            error.message
        );
        assert!(
            error.message.contains("known-keys.json"),
            "{}",
            error.message
        );
    }

    /// Rotation refuses to go backwards, for the same reason the index does.
    #[test]
    fn an_older_or_repeated_known_keys_document_is_refused() {
        assert!(moves_forward(10, 9).is_ok());

        for (sequence, last) in [(9, 9), (8, 9), (0, 1)] {
            let error = moves_forward(sequence, last).unwrap_err();
            assert_eq!(error.code, Code::Conflict, "{sequence} after {last}");
        }

        // Equal is refused as well as lower: re-serving the same document is
        // how a key removed in the next one stays.
        assert!(moves_forward(1, 1).is_err());
    }

    /// A retired key cannot be brought back by a document, however that
    /// document was signed — including by the leaked key itself.
    #[test]
    fn a_retired_key_is_skipped_when_a_document_names_it() {
        let current = Keys {
            trusted: vec![PublicKey(TEST_PUB.into())],
            retired: vec![PublicKey(OTHER_PUB.into())],
        };
        assert!(current.is_retired(&PublicKey(OTHER_PUB.into())));
        assert!(!current.is_retired(&PublicKey(TEST_PUB.into())));
    }

    #[test]
    fn a_key_id_is_short_and_printable() {
        let id = PublicKey(TEST_PUB.into()).id();
        assert_eq!(id.len(), 16);
        assert!(TEST_PUB.starts_with(&id));
    }
}
